Add systemd service script and fix other init scripts
Other changes:
 * Replace README by README.md
 * Add travis configuration
 * Fix testsuite and dependencies detection

diff --git a/scripts/freebsd/yaws b/scripts/freebsd/yaws
--- a/scripts/freebsd/yaws
+++ b/scripts/freebsd/yaws
@@ -3,32 +3,73 @@
 # Start up for the Yaws daemon. Use this script for FreeBSD versions 9 or greater.
 #
 
-# PROVIDE: yaws 
-# BEFORE:  DAEMON
+# REQUIRE: DAEMON
+# PROVIDE: yaws
 # KEYWORD: shutdown
 
 . /etc/rc.subr
 
-name="yaws"
+name=yaws
+rcvar=yaws_enable
+
+command="%bindir%/yaws"
+
 yaws_id="default" # By default we run with the default id
-start_precmd="${name}_prestart"
+start_cmd="yaws_start"
 stop_cmd="yaws_stop"
 status_cmd="yaws_status"
-command="%prefix%/bin/${name}"
-rcvar="yaws_enable"
+reload_cmd="yaws_reload"
 command_args=""
-required_files="%etcdir%/${name}/${name}.conf"
+extra_commands="reload"
+required_files="%etcdir%/yaws/yaws.conf"
 
-yaws_prestart() {
-	rc_flags="--id ${yaws_id} --daemon --heart --conf %etcdir%/${name}/${name}.conf ${rc_flags}"
+yaws_start() {
+    echo -n "Starting Yaws: "
+    ${command} --id ${yaws_id} --daemon --heart --conf %etcdir%/yaws/yaws.conf ${rc_flags}
+    ${command} --id ${yaws_id} --wait-started=10 > /dev/null
+    RETVAL=$?
+    if [ $RETVAL = 0 ]; then
+        echo "OK"
+    else
+        echo "FAILED"
+    fi
+    return  $RETVAL
 }
 
 yaws_stop() {
-	%prefix%/bin/yaws --id ${yaws_id} --stop
+    echo -n "Stopping Yaws: "
+    ${command} --id ${yaws_id} --stop > /dev/null
+    ${command} --id ${yaws_id} --wait-stopped=10 > /dev/null
+    RETVAL=$?
+    if [ $RETVAL = 0 ]; then
+        echo "OK"
+    else
+        echo "FAILED"
+    fi
+    return  $RETVAL
 }
 
 yaws_status() {
-	%prefix%/bin/yaws --id ${yaws_id} --status
+    ${command} --id ${yaws_id} --status > /dev/null
+    RETVAL=$?
+    if [ $RETVAL = 0 ]; then
+        echo "Yaws is running"
+    else
+        echo "Yaws is stopped"
+    fi
+    return  $RETVAL
+}
+
+yaws_reload() {
+    echo -n "Reloading Yaws: "
+    ${command} --id ${yaws_id} --hup > /dev/null
+    RETVAL=$?
+    if [ $RETVAL = 0 ]; then
+        echo "OK"
+    else
+        echo "FAILED"
+    fi
+    return  $RETVAL
 }
 
 load_rc_config $name
diff --git a/test/t1/Makefile.am b/test/t1/Makefile.am
--- a/test/t1/Makefile.am
+++ b/test/t1/Makefile.am
@@ -50,42 +50,62 @@ t2:
 	$(AM_V_at)$(SHELL) @srcdir@/runtest 131072 1048576 #8388608
 
 t3:
-	@echo "check-with-curl (max_num_cached_files = 0)"
-	$(AM_V_at)cp $(YAWS_CONF).orig $(YAWS_CONF)
-	$(AM_V_at)echo 'max_num_cached_files = 0' >> $(YAWS_CONF)
-	$(AM_V_at)$(top_builddir)/test/bin/yaws --id testid --hup >/dev/null
-	$(AM_V_at)$(CHECK_WITH_CURL)
+	$(AM_V_at)if [ -z $(CURL) ]; then				\
+	  echo "SKIPPED - curl is required to run these tests";		\
+	else								\
+	  echo "check-with-curl (max_num_cached_files = 0)";		\
+	  cp $(YAWS_CONF).orig $(YAWS_CONF);				\
+	  echo 'max_num_cached_files = 0' >> $(YAWS_CONF);		\
+	  $(top_builddir)/test/bin/yaws --id testid --hup >/dev/null;	\
+	  $(CHECK_WITH_CURL);						\
+	fi
 
 t4:
-	@echo "check-with-curl (max_num_cached_bytes = 0)"
-	$(AM_V_at)cp $(YAWS_CONF).orig $(YAWS_CONF)
-	$(AM_V_at)echo 'max_num_cached_bytes = 0' >> $(YAWS_CONF)
-	$(AM_V_at)$(top_builddir)/test/bin/yaws --id testid --hup >/dev/null
-	$(AM_V_at)$(CHECK_WITH_CURL)
+	$(AM_V_at)if [ -z $(CURL) ]; then				\
+	  echo "SKIPPED - curl is required to run these tests";		\
+	else								\
+	  echo "check-with-curl (max_num_cached_bytes = 0)";		\
+	  cp $(YAWS_CONF).orig $(YAWS_CONF);				\
+	  echo 'max_num_cached_bytes = 0' >> $(YAWS_CONF);		\
+	  $(top_builddir)/test/bin/yaws --id testid --hup >/dev/null;	\
+	  $(CHECK_WITH_CURL);						\
+	fi
 
 t5:
-	@echo "check-with-curl (max_size_cached_file = 0)"
-	$(AM_V_at)cp $(YAWS_CONF).orig $(YAWS_CONF)
-	$(AM_V_at)echo 'max_size_cached_file = 0' >> $(YAWS_CONF)
-	$(AM_V_at)$(top_builddir)/test/bin/yaws --id testid --hup >/dev/null
-	$(AM_V_at)$(CHECK_WITH_CURL)
+	$(AM_V_at)if [ -z $(CURL) ]; then				\
+	  echo "SKIPPED - curl is required to run these tests";		\
+	else								\
+	  echo "check-with-curl (max_size_cached_file = 0)";		\
+	  cp $(YAWS_CONF).orig $(YAWS_CONF);				\
+	  echo 'max_size_cached_file = 0' >> $(YAWS_CONF);		\
+	  $(top_builddir)/test/bin/yaws --id testid --hup >/dev/null;	\
+	  $(CHECK_WITH_CURL);						\
+	fi
 
 t6:
-	@echo "check-with-curl (max_num_cached_bytes = 5 / max_size_cached_file = 50)"
-	$(AM_V_at)cp $(YAWS_CONF).orig $(YAWS_CONF)
-	$(AM_V_at)echo 'max_num_cached_bytes = 5'  >> $(YAWS_CONF)
-	$(AM_V_at)echo 'max_size_cached_file = 50' >> $(YAWS_CONF)
-	$(AM_V_at)$(top_builddir)/test/bin/yaws --id testid --hup >/dev/null
-	$(AM_V_at)$(CHECK_WITH_CURL)
+	$(AM_V_at)if [ -z $(CURL) ]; then						\
+	  echo "SKIPPED - curl is required to run these tests";				\
+	else										\
+	  echo "check-with-curl (max_num_cached_bytes = 5 / max_size_cached_file = 50)";\
+	  cp $(YAWS_CONF).orig $(YAWS_CONF);						\
+	  echo 'max_num_cached_bytes = 5'  >> $(YAWS_CONF);				\
+	  echo 'max_size_cached_file = 50' >> $(YAWS_CONF);				\
+	  $(top_builddir)/test/bin/yaws --id testid --hup >/dev/null;			\
+	  $(CHECK_WITH_CURL);								\
+	fi
 
 # Verify redirection does not create URIs with multiple adjacent slashes Test
 # submitted by James Lee
 t7: newconf hup
-	@echo "redirect test"
-	$(AM_V_at)loc=`curl -s -m 5 -i http://localhost:8003/foo   |	\
-	  perl -ne 'print "$$1\n" if (m#Location:\s+http://(.+)#)' | 	\
-	  grep //`;							\
-	  [ "${loc}" = "" ] && exit 0 || exit 1
+	$(AM_V_at)if [ -z $(CURL) ]; then				\
+	  echo "SKIPPED - curl is required to run these tests";		\
+	else								\
+	  echo "redirect test";						\
+	  loc=`curl -s -m 5 -i http://localhost:8003/foo   |		\
+	    perl -ne 'print "$$1\n" if (m#Location:\s+http://(.+)#)' | 	\
+	    grep //`;							\
+	  [ "${loc}" = "" ] && exit 0 || exit 1;			\
+	fi
 
 json:
 	@echo "json test"
