Massive autotools refactoring & cleanup
Now, all makefile are generated by automake. This way, many things are more
configurable and maintainable.

Main (visible) changes:

 * Now, you can configure and compile Yaws outside the source directory. It is
   also possible to generate an archive for distribution, using the 'dist' target
   (from now, 'distcheck' target should always pass).

 * We track .erl dependencies using '-M*' flags of ERLC.

 * generated header 'yaws_configure.hrl' disappears. HAVE_SENDFILE,
   HAVE_ERLANG_SENDFILE and HAVE_CRYPTO_HASH macros are defined in ERLC flags.

 * yaws_generated:localinstall/0 function disappears (see comment about local
   install).

 * To create a windows installer, we just need to run the 'mkinstaller'
   target. Read win32/README.developer for details.

 * We use standard Erlang installation path for Yaws, relative to the erlang
   library directory (/usr/lib/erlang/lib). Now, '$(libdir)/yaws' is a link. We
   do the same for yapp application.

 * "local install" was removed. Now, to do a "developer install", we just need
   to set a prefix during the project configuration using --prefix option. So,
   you need to install yaws to test it.

 * DESTDIR variable is still supported.

 * scripts/make-release was rewritten to use 'dist' and 'mkinstaller' targets.

 * Installation of Yaws applications has slightly changed. Now they are
   installed in their own directory, in '$(localstatedir)/yaws'. So, chat
   application will be installed in '$(localstatedir)/yaws/chat', with 'www' and
   'ebin' subdirs.

Main targets (others than all/install/clean....):

  * all           : compile Yaws
  * debug         : compile Yaws with debug flags
  * clean         : remove files produced by all or debug target
  * install       : do a proper install of Yaws
  * doc or docs   : build the documentation
  * check or test : launch tests
  * cleantest     : remove files produced by check target
  * dialyzer      : run dialyzer on Yaws
  * mkinstaller   : build an installer for windows
  * cleaninstaller: remove files produced by mkinstaller target
  * apps          : compile Yaws applications (chat,mail,wiki,yapp)
  * cleanapps     : remove files produced by apps target
  * installapps   : install Yaws applications
  * fullinstall   : install + installapps
  * fullclean     : clean + cleantest + cleanapps + cleaninstaller

  To install an application, run: (cd application/{APP} && make install)

Of course, many things can be customized during configuration and Rebar still
works as expected. To do an install with (almost) the same tree than with
previous of Yaws, do:

  $> ./configure yawsdir=${prefix}/lib/yaws yappdir=${prefix}/lib/yapp \
        --sysconfdir=/etc --localstatedir=/var
  $> make install

Here is the default installation tree on my debian:

   usr
    ├── lib
    │   └── erlang
    │       └── lib
    │           ├── yapp-0.4.2
    │           │   ├── doc/
    │           │   ├── ebin/
    │           │   ├── examples/
    │           │   └── priv/docroot/
    │           └── yaws-1.98
    │               ├── ebin/
    │               ├── include/
    │               └── priv/
    │               ├── examples/
    │
    ├── local/bin/yaws
    │
    ├── local/etc/init.d/yaws
    ├── local/etc/yaws/
    ├── local/etc/mail/yaws-webmail.conf
    │
    ├── local/lib/pkgconfig/yaws.pc
    ├── local/lib/yapp -> /usr/lib/erlang/lib/yapp-0.4.2
    ├── local/lib/yaws -> /usr/lib/erlang/lib/yaws-1.98
    │
    ├── local/share/doc/yaws/yaws.pdf
    ├── local/share/man/{man1,man5}/
    │
    ├── local/var/log/yaws
    ├── local/var/run/yaws
    └── local/var/yaws
        ├── chat/{ebin,www}
        ├── mail/{ebin,www}
        ├── wiki/{ebin,www}
        └── www

diff --git a/test/t1/wgettest b/test/t1/wgettest
--- a/test/t1/wgettest
+++ b/test/t1/wgettest
@@ -1,19 +1,14 @@
 #!/bin/sh
 
-rm -rf localhost:8000
-wget -q -r http://localhost:8000
+wget -q -r http://localhost:8001
 # Give yaws some time to write out its report.log file
 count=10
 while [ $count -gt 0 ]; do
-    if [ ! -f logs/report.log ]; then
-        sleep 3
-    else
-        # log file written, now check it
-        # count lines to work around grep exit status portability issues
-        total=`cat logs/report.log | grep -v www/arg.yaws | \
-            grep -v www/arg2.yaws | grep -v ^=ERROR | grep ERROR 2>&1 | wc -l`
-        [ "$total" -eq 0 ] || exit 1
-    fi
+    # check it report.log
+    # count lines to work around grep exit status portability issues
+    total=`cat logs/report.log | grep -v www/arg.yaws | \
+        grep -v www/arg2.yaws | grep -v ^=ERROR | grep ERROR 2>&1 | wc -l`
+    [ "$total" -eq 0 ] || exit 1
     count=`expr $count - 1`
 done
 exit 0
