Fix #414: handle server name wildcards correctly
If a Host header contains <name>:<port> and the server name specifies
wildcard:<port>, match the <name> portion correctly against the
wildcard. Add a new unit test to verify this.

Change the default yaws.conf template to specify port numbers for
wildcard server names.

Fix the gen-yaws-conf script to verify PORT and SSLPORT are set.

diff --git a/scripts/gen-yaws-conf b/scripts/gen-yaws-conf
--- a/scripts/gen-yaws-conf
+++ b/scripts/gen-yaws-conf
@@ -5,6 +5,15 @@
 
 set -e
 
+if [ ! -n "$PORT" ]; then
+    echo 'error: PORT environment variable must be set' >&2
+    exit 1
+fi
+if [ ! -n "$SSLPORT" ]; then
+    echo 'error: SSLPORT environment variable must be set' >&2
+    exit 1
+fi
+
 cat yaws.conf.template                  | \
     ./Subst %yawsdir% "$YAWSDIR"        | \
     ./Subst %logdir%  "$LOGDIR"         | \
